name = "pyDBInfoscreen"
version = "1.1.0"
description = "Python bindings for https://github.com/derf/db-fakedisplay"
license = "GPLv3"
author = "Julian Metzler"
author_email = "git@mezgr.de"
requires = ['requests']
url = "https://github.com/Mezgrman/pyDBInfoscreen"
keywords = "train web api json departure arrival times"